
version: '3.5'
services:
  postgres:
    container_name: acs-db-container
    image: acs-db-image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
#      PGDATA: /data/postgres
#    volumes:
#       - postgres:/data/postgres
    ports:
      - '5432:5432'
#    networks:
#      - postgres
#    restart: unless-stopped
